export const ADDSLIDESHOW = "ADDSLIDESHOW";
export const GETSLIDESHOW = "GETSLIDESHOW";
export const DELETESLIDESHOW = "DELETESLIDESHOW";
export const EDITSLIDESHOW = "EDITSLIDESHOW";
export const UPLOAD = "UPLOAD";